sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/TheBlockchainManifesto.tex
- bibtex _build/TheBlockchainManifesto
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/TheBlockchainManifesto.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build tex/TheBlockchainManifesto.tex
deploy:
  provider: releases
  api_key:
    secure: IzuwWh0k4O4LuCG1ZdbwKKunmUEd3WV/5fi4YgaRND4rMmx7UkNFfrF7Irn6PvbtwVoACcKcQtNBtVyHa076lG7HYQXptW1x8FKNkF4GEJgW0pW8GEG9uu0DH3hNJfMNkdQLC9rXlGn4tKq9y7dI20qH/STqHPXm8GIX5fFm+kmqiGrnsuB6gu7QWOrBk891lZCalU/Lt1y67/prBQ1GDB6h7PaWGyWS7PQp9TM9tMyOcGvHkH4mdZPoCC514itvserT9E1WpbHoN5GEUrND7pss+Nk6YtqBSjYPvFtZHi6Xc1L3pRh54MazeU3fH72RvSt/97NT/VHQNQo+k27xMXdNZQgUUBLpkIT+q5RefBbUKdqMAcVN1VpevnaxAYuLQEVboF7mcZYlfNUHmC/g+aR69slZfnIOsD7nrS+H+hVa/9GnULAPMn1712zrupzijfDRLud6l8IsdyioVU+Fr3SFcT8uhO7lXylZahUviV08jkSH+k5ibK9gDyPI/mdPai36i3LfCeZSRTMmJ8Fbn31MsHe9ODltddCiK3H33tFnd9VumQJG+GDGrM+toc83x7jswO3jNQzOEBa4IiequwWKrmgr304DBIko94jDZNpngxK5FXwjeqE191uT21ncIzr/8edJsklLADQf1HaJGJAXlx4F5zQsZ22R0TVV9e4=
  file:
  - _build/TheBlockchainManifesto.pdf
  on:
    tags: true
